spring:
  datasource:
    url: jdbc:h2:mem:lg
    username: lg
    password: laundryGo!
    hikari:
      maximum-pool-size: 4
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.laundrygo.shorturl.repository: debug

shorturl:
  baseurl: localhost:8080